management:
  cloudfoundry:
    skip-ssl-validation: true
  security:
    enabled: false
  info:
    git:
      mode: full
  metrics:
    enable:
      root: false
      jvm: true
---
spring:
  jpa:
    generate-ddl: true


